name: Build and Test with Cargo

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: ubuntu-24.04-arm
            system: aarch64-linux
    uses: manic-systems/workflows/.github/workflows/rust-checks.yml@c6f105d06833433a442f13b1aee61ca9da9624d6
    with:
      os: ${{ matrix.os }}
      flake-check-command: nix build .#packages.${{ matrix.system }}.default && nix flake check --no-build
